version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
            - ./db-data:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "10521:8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
            - 10522:80
    depends_on:
            - web
    container_name: nginx
volumes:
        db-dasta:
